name: eva_pharma
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  circular_bottom_navigation: ^1.0.1
  flutter_swiper: ^1.1.6
  drawerbehavior: ^1.1.2
  flutter_slider_drawer: ^1.0.3
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.3.2+1
#  flappy_search_bar: 1.4.1







dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



  assets:
      - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
